num1 = int(input())
num2 = num1 * int(input())
num3 = num2 * int(input())
res = list(str(num3))

print(res.count('0'))
print(res.count('1'))
print(res.count('2'))
print(res.count('3'))
print(res.count('4'))
print(res.count('5'))
print(res.count('6'))
print(res.count('7'))
print(res.count('8'))
print(res.count('9'))